### ISSUE TITLE
打开订单空间时报错。

### ISSUE THREAD

**Issue by Jockeyvb** [LambdaIM/launch#21]
C:\Users\Administrator.SC-SERVER>C:\Users\Administrator.SC-SERVER\lambWallet\lambdastoragecli.exe gateway run     --broker.dht_gateway_addr 47.93.196.236:13000     --broker.validator_addr  47.93.196.236:13659     --broker.extra_key_file  C:\Users\Administrator.SC-SERVER\lambWallet\Wallet\lambda1j3z93m7l3fzujrs56jsh8h0l9t7k9c0hpgy3k3.keyinfo     --gateway.address  127.0.0.1:9678     --gateway.access_key  lambda      --gateway.secret_key  12345678      --broker.extra_order_id  70A4C94D16C706768EC992ED8559194E629E97F3      --home C:\Users\Administrator.SC-SERVER\lambWallet\orderS3
Password to sign with 'Jockeyvb2':
entering extra mode ...
imported wallet account:  lambda1j3z93m7l3fzujrs56jsh8h0l9t7k9c0hpgy3k3
try to sync orders under this account...
sync single order begin, This may take some time...
http://47.93.196.236:13659/market/user/matchorders/lambda1j3z93m7l3fzujrs56jsh8h0l9t7k9c0hpgy3k3
error: query address DEXM8SztyxrdzTVBWTf9ReN2VVnoH2s6Bn5XGaiVuR75 from 47.93.196.236:13000 DHT failed: error: query node DEXM8SztyxrdzTVBWTf9ReN2VVnoH2s6Bn5XGaiVuR75 from 47.93.196.236:13000 failed
Error: error: query node DEXM8SztyxrdzTVBWTf9ReN2VVnoH2s6Bn5XGaiVuR75 from 47.93.196.236:13000 failed

**Comment by lvxv** [comment]
minernode info
storagenode info

需要先配置，里面的服务端口，可以访问。
打开订单，是去从storagenode 同步token，如果服务不可访问，就会报错。
