### ISSUE TITLE
how to run miner

### ISSUE THREAD

**Issue by ajffdnt** [LambdaIM/launch#4]
![image](https://user-images.githubusercontent.com/4186486/64677782-db487b00-d4aa-11e9-9796-5895fb13add3.png)
![image](https://user-images.githubusercontent.com/4186486/64678283-da641900-d4ab-11e9-8d77-a4c6afc10af2.png)

how much utbb are needed in the last step?  what is utbb?  is 1TBB = 1000000000utbb?
I see this step like transaction, not run miner? how to run miner?
Hope reply soon. Thank you!

**Comment by lvxv** [comment]
1TBB == 10^6utbb
you can staking TBB to become miner and get a part of the block reward.
miner does not need to run any program now,  it will be able to store mining in future versions.

**Comment by ajffdnt** [comment]
Can I only get mortgage income now? When can I run a program for real storage mining?

**Comment by lvxv** [comment]
yes.  for the mining version, please pay attention to the announcement of lambda community.

**Comment by lvxv** [comment]
The mining version has released a beta version.
